"""Neue Migration

Revision ID: 8deb5d7d7d7c
Revises: c5b70259eba1
Create Date: 2025-01-16 21:21:16.646028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8deb5d7d7d7c'
down_revision = 'c5b70259eba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('license_tier', sa.String(length=20), nullable=True),
    sa.Column('license_expiry', sa.DateTime(), nullable=True),
    sa.Column('gpt_used_count', sa.Integer(), nullable=True),
    sa.Column('gpt_allowed_count', sa.Integer(), nullable=True),
    sa.Column('addons', sa.String(length=200), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('current_session_token', sa.String(length=64), nullable=True),
    sa.Column('twofa_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('payment_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_log')
    op.drop_table('user')
    # ### end Alembic commands ###
